version: "1"
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: sql_store
        ports:
            - "5432:5432"
    web:
        build: .
        depends_on:
            - db
        ports:
            - "5000:5000"
